/*
 * ThingSpaceConnectivityManagementAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThingSpaceConnectivityManagementAPI.PCL;

namespace ThingSpaceConnectivityManagementAPI.PCL.Models
{
    public class AddDevicesRequest : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string accountName;
        private List<KvPair> customFields;
        private List<DeviceList> devicesToAdd;
        private string groupName;
        private string skuNumber;
        private string state;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("accountName")]
        public string AccountName 
        { 
            get 
            {
                return this.accountName; 
            } 
            set 
            {
                this.accountName = value;
                onPropertyChanged("AccountName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("customFields")]
        public List<KvPair> CustomFields 
        { 
            get 
            {
                return this.customFields; 
            } 
            set 
            {
                this.customFields = value;
                onPropertyChanged("CustomFields");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("devicesToAdd")]
        public List<DeviceList> DevicesToAdd 
        { 
            get 
            {
                return this.devicesToAdd; 
            } 
            set 
            {
                this.devicesToAdd = value;
                onPropertyChanged("DevicesToAdd");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("groupName")]
        public string GroupName 
        { 
            get 
            {
                return this.groupName; 
            } 
            set 
            {
                this.groupName = value;
                onPropertyChanged("GroupName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("skuNumber")]
        public string SkuNumber 
        { 
            get 
            {
                return this.skuNumber; 
            } 
            set 
            {
                this.skuNumber = value;
                onPropertyChanged("SkuNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("state")]
        public string State 
        { 
            get 
            {
                return this.state; 
            } 
            set 
            {
                this.state = value;
                onPropertyChanged("State");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 