/*
 * ThingSpaceConnectivityManagementAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThingSpaceConnectivityManagementAPI.PCL;

namespace ThingSpaceConnectivityManagementAPI.PCL.Models
{
    public class CarrierActivateRequest : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string accountName;
        private string carrierIpPoolName;
        private string carrierName;
        private string costCenterCode;
        private List<KvPair> customFields;
        private List<DeviceList> devices;
        private string groupName;
        private string leadId;
        private string mdnZipCode;
        private PlaceOfUse primaryPlaceOfUse;
        private string publicIpRestriction;
        private string servicePlan;
        private string skuNumber;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("accountName")]
        public string AccountName 
        { 
            get 
            {
                return this.accountName; 
            } 
            set 
            {
                this.accountName = value;
                onPropertyChanged("AccountName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("carrierIpPoolName")]
        public string CarrierIpPoolName 
        { 
            get 
            {
                return this.carrierIpPoolName; 
            } 
            set 
            {
                this.carrierIpPoolName = value;
                onPropertyChanged("CarrierIpPoolName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("carrierName")]
        public string CarrierName 
        { 
            get 
            {
                return this.carrierName; 
            } 
            set 
            {
                this.carrierName = value;
                onPropertyChanged("CarrierName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("costCenterCode")]
        public string CostCenterCode 
        { 
            get 
            {
                return this.costCenterCode; 
            } 
            set 
            {
                this.costCenterCode = value;
                onPropertyChanged("CostCenterCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("customFields")]
        public List<KvPair> CustomFields 
        { 
            get 
            {
                return this.customFields; 
            } 
            set 
            {
                this.customFields = value;
                onPropertyChanged("CustomFields");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("devices")]
        public List<DeviceList> Devices 
        { 
            get 
            {
                return this.devices; 
            } 
            set 
            {
                this.devices = value;
                onPropertyChanged("Devices");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("groupName")]
        public string GroupName 
        { 
            get 
            {
                return this.groupName; 
            } 
            set 
            {
                this.groupName = value;
                onPropertyChanged("GroupName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("leadId")]
        public string LeadId 
        { 
            get 
            {
                return this.leadId; 
            } 
            set 
            {
                this.leadId = value;
                onPropertyChanged("LeadId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("mdnZipCode")]
        public string MdnZipCode 
        { 
            get 
            {
                return this.mdnZipCode; 
            } 
            set 
            {
                this.mdnZipCode = value;
                onPropertyChanged("MdnZipCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("primaryPlaceOfUse")]
        public PlaceOfUse PrimaryPlaceOfUse 
        { 
            get 
            {
                return this.primaryPlaceOfUse; 
            } 
            set 
            {
                this.primaryPlaceOfUse = value;
                onPropertyChanged("PrimaryPlaceOfUse");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("publicIpRestriction")]
        public string PublicIpRestriction 
        { 
            get 
            {
                return this.publicIpRestriction; 
            } 
            set 
            {
                this.publicIpRestriction = value;
                onPropertyChanged("PublicIpRestriction");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("servicePlan")]
        public string ServicePlan 
        { 
            get 
            {
                return this.servicePlan; 
            } 
            set 
            {
                this.servicePlan = value;
                onPropertyChanged("ServicePlan");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("skuNumber")]
        public string SkuNumber 
        { 
            get 
            {
                return this.skuNumber; 
            } 
            set 
            {
                this.skuNumber = value;
                onPropertyChanged("SkuNumber");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 