/*
 * ThingSpaceConnectivityManagementAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThingSpaceConnectivityManagementAPI.PCL;

namespace ThingSpaceConnectivityManagementAPI.PCL.Models
{
    public class ChangeDeviceIdRequest : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private bool? assignNonGeoMdn;
        private string change4gOption;
        private List<DeviceId> deviceIds;
        private List<DeviceId> deviceIdsTo;
        private string npaNxx;
        private string servicePlan;
        private string zipCode;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("assignNonGeoMdn")]
        public bool? AssignNonGeoMdn 
        { 
            get 
            {
                return this.assignNonGeoMdn; 
            } 
            set 
            {
                this.assignNonGeoMdn = value;
                onPropertyChanged("AssignNonGeoMdn");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("change4gOption")]
        public string Change4gOption 
        { 
            get 
            {
                return this.change4gOption; 
            } 
            set 
            {
                this.change4gOption = value;
                onPropertyChanged("Change4gOption");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("deviceIds")]
        public List<DeviceId> DeviceIds 
        { 
            get 
            {
                return this.deviceIds; 
            } 
            set 
            {
                this.deviceIds = value;
                onPropertyChanged("DeviceIds");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("deviceIdsTo")]
        public List<DeviceId> DeviceIdsTo 
        { 
            get 
            {
                return this.deviceIdsTo; 
            } 
            set 
            {
                this.deviceIdsTo = value;
                onPropertyChanged("DeviceIdsTo");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("npaNxx")]
        public string NpaNxx 
        { 
            get 
            {
                return this.npaNxx; 
            } 
            set 
            {
                this.npaNxx = value;
                onPropertyChanged("NpaNxx");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("servicePlan")]
        public string ServicePlan 
        { 
            get 
            {
                return this.servicePlan; 
            } 
            set 
            {
                this.servicePlan = value;
                onPropertyChanged("ServicePlan");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("zipCode")]
        public string ZipCode 
        { 
            get 
            {
                return this.zipCode; 
            } 
            set 
            {
                this.zipCode = value;
                onPropertyChanged("ZipCode");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 