/*
 * ThingSpaceConnectivityManagementAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThingSpaceConnectivityManagementAPI.PCL;

namespace ThingSpaceConnectivityManagementAPI.PCL.Models
{
    public class CustomFieldsUpdateRequest : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string accountName;
        private List<KvPair> customFields;
        private List<KvPair> customFieldsToUpdate;
        private List<DeviceList> devices;
        private string groupName;
        private string servicePlan;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("accountName")]
        public string AccountName 
        { 
            get 
            {
                return this.accountName; 
            } 
            set 
            {
                this.accountName = value;
                onPropertyChanged("AccountName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("customFields")]
        public List<KvPair> CustomFields 
        { 
            get 
            {
                return this.customFields; 
            } 
            set 
            {
                this.customFields = value;
                onPropertyChanged("CustomFields");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("customFieldsToUpdate")]
        public List<KvPair> CustomFieldsToUpdate 
        { 
            get 
            {
                return this.customFieldsToUpdate; 
            } 
            set 
            {
                this.customFieldsToUpdate = value;
                onPropertyChanged("CustomFieldsToUpdate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("devices")]
        public List<DeviceList> Devices 
        { 
            get 
            {
                return this.devices; 
            } 
            set 
            {
                this.devices = value;
                onPropertyChanged("Devices");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("groupName")]
        public string GroupName 
        { 
            get 
            {
                return this.groupName; 
            } 
            set 
            {
                this.groupName = value;
                onPropertyChanged("GroupName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("servicePlan")]
        public string ServicePlan 
        { 
            get 
            {
                return this.servicePlan; 
            } 
            set 
            {
                this.servicePlan = value;
                onPropertyChanged("ServicePlan");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 