/*
 * ThingSpaceConnectivityManagementAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThingSpaceConnectivityManagementAPI.PCL;

namespace ThingSpaceConnectivityManagementAPI.PCL.Models
{
    public class Device : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string accountName;
        private string billingCycleEndDate;
        private List<CarrierInformation> carrierInformations;
        private bool? connected;
        private string createdAt;
        private List<KvPair> customFields;
        private List<DeviceId> deviceIds;
        private List<KvPair> extendedAttributes;
        private List<string> groupNames;
        private string ipAddress;
        private string lastActivationBy;
        private string lastActivationDate;
        private string lastConnectionDate;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("accountName")]
        public string AccountName 
        { 
            get 
            {
                return this.accountName; 
            } 
            set 
            {
                this.accountName = value;
                onPropertyChanged("AccountName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("billingCycleEndDate")]
        public string BillingCycleEndDate 
        { 
            get 
            {
                return this.billingCycleEndDate; 
            } 
            set 
            {
                this.billingCycleEndDate = value;
                onPropertyChanged("BillingCycleEndDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("carrierInformations")]
        public List<CarrierInformation> CarrierInformations 
        { 
            get 
            {
                return this.carrierInformations; 
            } 
            set 
            {
                this.carrierInformations = value;
                onPropertyChanged("CarrierInformations");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("connected")]
        public bool? Connected 
        { 
            get 
            {
                return this.connected; 
            } 
            set 
            {
                this.connected = value;
                onPropertyChanged("Connected");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("createdAt")]
        public string CreatedAt 
        { 
            get 
            {
                return this.createdAt; 
            } 
            set 
            {
                this.createdAt = value;
                onPropertyChanged("CreatedAt");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("customFields")]
        public List<KvPair> CustomFields 
        { 
            get 
            {
                return this.customFields; 
            } 
            set 
            {
                this.customFields = value;
                onPropertyChanged("CustomFields");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("deviceIds")]
        public List<DeviceId> DeviceIds 
        { 
            get 
            {
                return this.deviceIds; 
            } 
            set 
            {
                this.deviceIds = value;
                onPropertyChanged("DeviceIds");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("extendedAttributes")]
        public List<KvPair> ExtendedAttributes 
        { 
            get 
            {
                return this.extendedAttributes; 
            } 
            set 
            {
                this.extendedAttributes = value;
                onPropertyChanged("ExtendedAttributes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("groupNames")]
        public List<string> GroupNames 
        { 
            get 
            {
                return this.groupNames; 
            } 
            set 
            {
                this.groupNames = value;
                onPropertyChanged("GroupNames");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ipAddress")]
        public string IpAddress 
        { 
            get 
            {
                return this.ipAddress; 
            } 
            set 
            {
                this.ipAddress = value;
                onPropertyChanged("IpAddress");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("lastActivationBy")]
        public string LastActivationBy 
        { 
            get 
            {
                return this.lastActivationBy; 
            } 
            set 
            {
                this.lastActivationBy = value;
                onPropertyChanged("LastActivationBy");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("lastActivationDate")]
        public string LastActivationDate 
        { 
            get 
            {
                return this.lastActivationDate; 
            } 
            set 
            {
                this.lastActivationDate = value;
                onPropertyChanged("LastActivationDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("lastConnectionDate")]
        public string LastConnectionDate 
        { 
            get 
            {
                return this.lastConnectionDate; 
            } 
            set 
            {
                this.lastConnectionDate = value;
                onPropertyChanged("LastConnectionDate");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 