/*
 * ThingSpaceConnectivityManagementAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThingSpaceConnectivityManagementAPI.PCL;

namespace ThingSpaceConnectivityManagementAPI.PCL.Models
{
    public class DeviceListRequest : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string accountName;
        private string currentState;
        private List<KvPair> customFields;
        private DeviceId deviceId;
        private string earliest;
        private string groupName;
        private string latest;
        private string servicePlan;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("accountName")]
        public string AccountName 
        { 
            get 
            {
                return this.accountName; 
            } 
            set 
            {
                this.accountName = value;
                onPropertyChanged("AccountName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("currentState")]
        public string CurrentState 
        { 
            get 
            {
                return this.currentState; 
            } 
            set 
            {
                this.currentState = value;
                onPropertyChanged("CurrentState");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("customFields")]
        public List<KvPair> CustomFields 
        { 
            get 
            {
                return this.customFields; 
            } 
            set 
            {
                this.customFields = value;
                onPropertyChanged("CustomFields");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("deviceId")]
        public DeviceId DeviceId 
        { 
            get 
            {
                return this.deviceId; 
            } 
            set 
            {
                this.deviceId = value;
                onPropertyChanged("DeviceId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("earliest")]
        public string Earliest 
        { 
            get 
            {
                return this.earliest; 
            } 
            set 
            {
                this.earliest = value;
                onPropertyChanged("Earliest");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("groupName")]
        public string GroupName 
        { 
            get 
            {
                return this.groupName; 
            } 
            set 
            {
                this.groupName = value;
                onPropertyChanged("GroupName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("latest")]
        public string Latest 
        { 
            get 
            {
                return this.latest; 
            } 
            set 
            {
                this.latest = value;
                onPropertyChanged("Latest");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("servicePlan")]
        public string ServicePlan 
        { 
            get 
            {
                return this.servicePlan; 
            } 
            set 
            {
                this.servicePlan = value;
                onPropertyChanged("ServicePlan");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 