/*
 * ThingSpaceConnectivityManagementAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThingSpaceConnectivityManagementAPI.PCL;

namespace ThingSpaceConnectivityManagementAPI.PCL.Models
{
    public class GroupUpdateRequest : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private List<DeviceId> devicesToAdd;
        private List<DeviceId> devicesToRemove;
        private string newGroupDescription;
        private string newGroupName;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("devicesToAdd")]
        public List<DeviceId> DevicesToAdd 
        { 
            get 
            {
                return this.devicesToAdd; 
            } 
            set 
            {
                this.devicesToAdd = value;
                onPropertyChanged("DevicesToAdd");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("devicesToRemove")]
        public List<DeviceId> DevicesToRemove 
        { 
            get 
            {
                return this.devicesToRemove; 
            } 
            set 
            {
                this.devicesToRemove = value;
                onPropertyChanged("DevicesToRemove");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("newGroupDescription")]
        public string NewGroupDescription 
        { 
            get 
            {
                return this.newGroupDescription; 
            } 
            set 
            {
                this.newGroupDescription = value;
                onPropertyChanged("NewGroupDescription");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("newGroupName")]
        public string NewGroupName 
        { 
            get 
            {
                return this.newGroupName; 
            } 
            set 
            {
                this.newGroupName = value;
                onPropertyChanged("NewGroupName");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 