/*
 * ThingSpaceConnectivityManagementAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThingSpaceConnectivityManagementAPI.PCL;

namespace ThingSpaceConnectivityManagementAPI.PCL.Models
{
    public class ProvisioningHistory : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string eventBy;
        private string eventType;
        private List<KvPair> extendedAttributes;
        private string mdn;
        private string msisdn;
        private string occurredAt;
        private string servicePlan;
        private string status;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("eventBy")]
        public string EventBy 
        { 
            get 
            {
                return this.eventBy; 
            } 
            set 
            {
                this.eventBy = value;
                onPropertyChanged("EventBy");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("eventType")]
        public string EventType 
        { 
            get 
            {
                return this.eventType; 
            } 
            set 
            {
                this.eventType = value;
                onPropertyChanged("EventType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("extendedAttributes")]
        public List<KvPair> ExtendedAttributes 
        { 
            get 
            {
                return this.extendedAttributes; 
            } 
            set 
            {
                this.extendedAttributes = value;
                onPropertyChanged("ExtendedAttributes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("mdn")]
        public string Mdn 
        { 
            get 
            {
                return this.mdn; 
            } 
            set 
            {
                this.mdn = value;
                onPropertyChanged("Mdn");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("msisdn")]
        public string Msisdn 
        { 
            get 
            {
                return this.msisdn; 
            } 
            set 
            {
                this.msisdn = value;
                onPropertyChanged("Msisdn");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("occurredAt")]
        public string OccurredAt 
        { 
            get 
            {
                return this.occurredAt; 
            } 
            set 
            {
                this.occurredAt = value;
                onPropertyChanged("OccurredAt");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("servicePlan")]
        public string ServicePlan 
        { 
            get 
            {
                return this.servicePlan; 
            } 
            set 
            {
                this.servicePlan = value;
                onPropertyChanged("ServicePlan");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("status")]
        public string Status 
        { 
            get 
            {
                return this.status; 
            } 
            set 
            {
                this.status = value;
                onPropertyChanged("Status");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 