/*
 * ThingSpaceConnectivityManagementAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThingSpaceConnectivityManagementAPI.PCL;

namespace ThingSpaceConnectivityManagementAPI.PCL.Models
{
    public class ServicePlanResponse : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string carrierServicePlanCode;
        private string code;
        private List<KvPair> extendedAttributes;
        private string name;
        private long? sizeKb;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("carrierServicePlanCode")]
        public string CarrierServicePlanCode 
        { 
            get 
            {
                return this.carrierServicePlanCode; 
            } 
            set 
            {
                this.carrierServicePlanCode = value;
                onPropertyChanged("CarrierServicePlanCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("code")]
        public string Code 
        { 
            get 
            {
                return this.code; 
            } 
            set 
            {
                this.code = value;
                onPropertyChanged("Code");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("extendedAttributes")]
        public List<KvPair> ExtendedAttributes 
        { 
            get 
            {
                return this.extendedAttributes; 
            } 
            set 
            {
                this.extendedAttributes = value;
                onPropertyChanged("ExtendedAttributes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("sizeKb")]
        public long? SizeKb 
        { 
            get 
            {
                return this.sizeKb; 
            } 
            set 
            {
                this.sizeKb = value;
                onPropertyChanged("SizeKb");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 