/*
 * ThingSpaceConnectivityManagementAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThingSpaceConnectivityManagementAPI.PCL;

namespace ThingSpaceConnectivityManagementAPI.PCL.Models
{
    public class Usage : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private long? bytesUsed;
        private List<KvPair> extendedAttributes;
        private string servicePlan;
        private int? smsUsed;
        private string source;
        private string timestamp;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("bytesUsed")]
        public long? BytesUsed 
        { 
            get 
            {
                return this.bytesUsed; 
            } 
            set 
            {
                this.bytesUsed = value;
                onPropertyChanged("BytesUsed");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("extendedAttributes")]
        public List<KvPair> ExtendedAttributes 
        { 
            get 
            {
                return this.extendedAttributes; 
            } 
            set 
            {
                this.extendedAttributes = value;
                onPropertyChanged("ExtendedAttributes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("servicePlan")]
        public string ServicePlan 
        { 
            get 
            {
                return this.servicePlan; 
            } 
            set 
            {
                this.servicePlan = value;
                onPropertyChanged("ServicePlan");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("smsUsed")]
        public int? SmsUsed 
        { 
            get 
            {
                return this.smsUsed; 
            } 
            set 
            {
                this.smsUsed = value;
                onPropertyChanged("SmsUsed");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("source")]
        public string Source 
        { 
            get 
            {
                return this.source; 
            } 
            set 
            {
                this.source = value;
                onPropertyChanged("Source");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("timestamp")]
        public string Timestamp 
        { 
            get 
            {
                return this.timestamp; 
            } 
            set 
            {
                this.timestamp = value;
                onPropertyChanged("Timestamp");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 