/*
 * ThingSpaceConnectivityManagementAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ThingSpaceConnectivityManagementAPI.PCL.Http.Client;

using ThingSpaceConnectivityManagementAPI.PCL.Models;
using ThingSpaceConnectivityManagementAPI.PCL;

namespace ThingSpaceConnectivityManagementAPI.PCL.Exceptions
{
    public class RestErrorResponseException : APIException 
    {
        // These fields hold the values for the public properties.
        private string errorCode;
        private string errorMessage;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("errorCode")]
        public string ErrorCode 
        { 
            get 
            {
                return this.errorCode; 
            } 
            private set 
            {
                this.errorCode = value;
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("errorMessage")]
        public string ErrorMessage 
        { 
            get 
            {
                return this.errorMessage; 
            } 
            private set 
            {
                this.errorMessage = value;
            }
        }

        /// <summary>
        /// Initialization constructor
        /// </summary>
        /// <param name="reason"> The reason for throwing exception </param>
        /// <param name="context"> The HTTP context that encapsulates request and response objects </param>
        public RestErrorResponseException(string reason, HttpContext context)
            : base(reason, context)
        {
        }
    }
} 