/*
 * ThingSpaceConnectivityManagementAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
using System;

namespace ThingSpaceConnectivityManagementAPI.PCL
{
    public partial class Configuration
    {
        //The base Uri for API calls
        public static string BaseUri = "https://example.com/api/m2m/v1";

        //TODO: Replace the ApiKey with an appropriate value
        public static string ApiKey = "";

    }
}