/*
 * ThingSpaceConnectivityManagementAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
using System;
using ThingSpaceConnectivityManagementAPI.PCL.Controllers;
using ThingSpaceConnectivityManagementAPI.PCL.Http.Client;

namespace ThingSpaceConnectivityManagementAPI.PCL
{
    public partial class ThingSpaceConnectivityManagementAPIClient
    {

        /// <summary>
        /// Singleton access to Sms controller
        /// </summary>
        public SmsController Sms
        {
            get
            {
                return ThingSpaceConnectivityManagementAPI.PCL.Controllers.SmsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Session controller
        /// </summary>
        public SessionController Session
        {
            get
            {
                return ThingSpaceConnectivityManagementAPI.PCL.Controllers.SessionController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Plans controller
        /// </summary>
        public PlansController Plans
        {
            get
            {
                return ThingSpaceConnectivityManagementAPI.PCL.Controllers.PlansController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Leads controller
        /// </summary>
        public LeadsController Leads
        {
            get
            {
                return ThingSpaceConnectivityManagementAPI.PCL.Controllers.LeadsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Groups controller
        /// </summary>
        public GroupsController Groups
        {
            get
            {
                return ThingSpaceConnectivityManagementAPI.PCL.Controllers.GroupsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Devices controller
        /// </summary>
        public DevicesController Devices
        {
            get
            {
                return ThingSpaceConnectivityManagementAPI.PCL.Controllers.DevicesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Callbacks controller
        /// </summary>
        public CallbacksController Callbacks
        {
            get
            {
                return ThingSpaceConnectivityManagementAPI.PCL.Controllers.CallbacksController.Instance;
            }
        }

        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        
        /// <summary>
        /// Default constructor
        /// </summary>
        public ThingSpaceConnectivityManagementAPIClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public ThingSpaceConnectivityManagementAPIClient(string apiKey)
        {
            Configuration.ApiKey = apiKey;
        }
    }
}